spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
